# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/event_emitter/all/event_emitter.rbi
#
# event_emitter-0.2.6

module EventEmitter
  def self.apply(object); end
  def self.included(klass); end
end
module EventEmitter::ClassMethods
end
module EventEmitter::InstanceMethods
  def __events; end
  def add_listener(type, params = nil, &block); end
  def emit(type, *data); end
  def on(type, params = nil, &block); end
  def once(type, &block); end
  def remove_listener(id_or_type); end
end
