# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/websocket-client-simple/all/websocket-client-simple.rbi
#
# websocket-client-simple-0.9.0

module WebSocket
end
module WebSocket::Client
end
module WebSocket::Client::Simple
  def self.connect(url, options = nil); end
end
class WebSocket::Client::Simple::Client
  def close; end
  def closed?; end
  def connect(url, options = nil); end
  def handshake; end
  def open?; end
  def send(data, opt = nil); end
  def thread; end
  def url; end
  include EventEmitter
  include EventEmitter::InstanceMethods
end
